name: CI/CD Pipeline & Docker Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow matplotlib seaborn joblib scipy pyarrow

      - name: Train / log model with MLflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get Run ID
        run: |
          RUN_ID=$(ls MLProject/mlruns/0/ | grep -E '^[a-f0-9]{32}$' | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Saving model as artifact to github actions
        uses: actions/upload-artifact@v4
        with:
          name: heart-disease-model-artifact
          path: MLProject/mlruns/0/${{ env.RUN_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build model serving image with MLflow
        run: |
          mlflow models build-docker \
            --model-uri "MLProject/mlruns/0/${{ env.RUN_ID }}/model" \
            --name "${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest" \
            --enable-mlserver

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest